import type { DriverData } from '../types/driver'
import type { FleetAsset } from '../types/fleet'
import { buildFleetCopilotContext, type CopilotContext } from './geminiCopilotHelpers'
import type { OperationsSnapshot } from '../types/operations'

let snapshotVersionCounter = 0

export type FleetSnapshot = {
  /** Monotonic diagnostic identifier — not generated by Gemini. */
  snapshotVersion: number
  /** ISO-8601 capture time — diagnostic only, no sensitive data. */
  snapshotCapturedAt: string
  /** Authoritative Copilot context for this capture. */
  context: CopilotContext
}

/** Resets the monotonic version counter — for tests only. */
export function resetFleetSnapshotVersionCounter(): void {
  snapshotVersionCounter = 0
}

/**
 * Creates an authoritative request-time snapshot from the current authorized fleet state.
 * Simulated telemetry values reflect the exact moment of capture; they are not frozen globally.
 */
export function createFleetSnapshot(
  assets: FleetAsset[],
  drivers: DriverData[],
  capturedAt: Date = new Date(),
): FleetSnapshot {
  snapshotVersionCounter += 1
  const snapshotVersion = snapshotVersionCounter
  const snapshotCapturedAt = capturedAt.toISOString()

  const baseContext = buildFleetCopilotContext(
    assets.map((asset) => ({
      assetId: asset.assetId,
      driverName: asset.driverName,
      statusLabel: asset.statusLabel,
    })),
    drivers.map((driver) => ({
      fullName: driver.fullName,
      expiryDate: driver.expiryDate,
    })),
  )

  const context: CopilotContext = {
    ...baseContext,
    snapshotVersion,
    snapshotCapturedAt,
  }

  return { snapshotVersion, snapshotCapturedAt, context }
}

/** Request-time Copilot context from the latest authorized fleet rows. */
export function captureRequestTimeCopilotContext(
  assets: FleetAsset[],
  drivers: DriverData[],
  capturedAt: Date = new Date(),
): CopilotContext {
  return createFleetSnapshot(assets, drivers, capturedAt).context
}

/** Merges deterministic operations snapshot fields into a fleet capture. */
export function mergeOpsSnapshotIntoContext(
  fleetSnapshot: FleetSnapshot,
  ops: OperationsSnapshot,
): CopilotContext {
  return {
    ...fleetSnapshot.context,
    fleetHealthSummary: ops.fleetHealthSummary,
    operationalPriorities: ops.operationalPriorities,
    recommendedActions: ops.recommendedActions,
  }
}
